export default function TermsPage() {
  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,600;0,700;1,400;1,600&family=Inter:wght@300;400;500;600&display=swap');
        * { box-sizing: border-box; margin: 0; padding: 0; }
        :root {
          --navy-deep: #0d1426;
          --gold: #c4a55a; --gold-light: #dfc080;
          --text-main: #eeeaf5; --text-muted: #9490b2; --text-dim: #5e5a7a;
          --border: rgba(196,165,90,0.16);
        }
        body { font-family: 'Inter', sans-serif; background: var(--navy-deep); color: var(--text-main); min-height: 100vh; }
        .page {
          min-height: 100vh;
          background: radial-gradient(ellipse at 10% 5%, rgba(196,165,90,0.05) 0%, transparent 40%),
                      radial-gradient(ellipse at 90% 95%, rgba(30,45,90,0.7) 0%, transparent 50%),
                      var(--navy-deep);
          display: flex; flex-direction: column; align-items: center; padding: 3rem 1rem;
        }
        .card {
          background: rgba(20,30,65,0.65); border: 1px solid var(--border);
          border-radius: 16px; backdrop-filter: blur(18px);
          width: 100%; max-width: 700px; padding: 3rem 3.5rem;
        }
        .logo-wrap { display: flex; justify-content: center; margin-bottom: 2rem; }
        .logo-wrap img { height: 64px; width: auto; object-fit: contain; }
        .headline { font-family: 'Playfair Display', serif; font-size: 2rem; font-weight: 400; color: var(--text-main); margin-bottom: 0.5rem; }
        .headline em { font-style: italic; color: var(--gold-light); }
        .updated { font-size: 0.75rem; color: var(--text-dim); margin-bottom: 2rem; }
        .divider-gold { width: 48px; height: 2px; background: linear-gradient(90deg, var(--gold), transparent); margin: 1.5rem 0; }
        .section-title { font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.14em; color: var(--gold); font-weight: 700; margin-bottom: 0.6rem; margin-top: 1.75rem; }
        .body-text { font-size: 0.91rem; color: var(--text-muted); line-height: 1.85; font-weight: 300; }
        .body-text + .body-text { margin-top: 0.75rem; }
        .divider { height: 1px; background: rgba(196,165,90,0.1); margin: 1.5rem 0; }
        .back-link { display: inline-flex; align-items: center; gap: 0.4rem; font-size: 0.8rem; color: var(--text-dim); text-decoration: none; margin-bottom: 2rem; transition: color 0.15s; }
        .back-link:hover { color: var(--gold); }
        .footer { text-align: center; margin-top: 2rem; padding-top: 1.25rem; border-top: 1px solid rgba(196,165,90,0.1); font-size: 0.75rem; color: var(--text-dim); }
        .footer a { color: var(--text-dim); text-decoration: none; transition: color 0.15s; }
        .footer a:hover { color: var(--gold); }
      `}</style>
      <div className="page">
        <div className="card">
          <div className="logo-wrap">
            <img src="/logo.png" alt="Compass AI" />
          </div>
          <a href="/" className="back-link">
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
              <path d="M9 11L5 7l4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
            Back to assessment
          </a>
          <h1 className="headline">Terms of <em>Use</em></h1>
          <div className="updated">Last updated: March 2026</div>
          <div className="divider-gold" />

          <div className="section-title">No Legal Advice</div>
          <p className="body-text">
            Compass AI is an informational tool designed to help organizations understand the AI governance landscape. The profiles, recommendations, and content generated by this tool do not constitute legal advice and should not be relied upon as such. No attorney-client relationship is formed through your use of this service.
          </p>
          <p className="body-text">
            Before making governance decisions, implementing compliance programs, or relying on any output from this tool, you should consult with a qualified attorney, compliance professional, or regulatory expert who can assess your specific situation.
          </p>

          <div className="divider" />

          <div className="section-title">No Warranty on Results</div>
          <p className="body-text">
            The governance profiles generated by Compass AI are produced by an AI model based on the answers you provide. While we design our prompts carefully to produce accurate and relevant guidance, we make no warranties, express or implied, about the accuracy, completeness, or fitness for purpose of any output. AI-generated content can contain errors or omissions.
          </p>
          <p className="body-text">
            Regulatory requirements change frequently. Laws applicable to AI governance are evolving rapidly across all jurisdictions. You are responsible for verifying that any guidance you receive reflects current law and applies to your specific circumstances.
          </p>

          <div className="divider" />

          <div className="section-title">No Data Retention</div>
          <p className="body-text">
            Your assessment responses are transmitted to the Anthropic API to generate your governance profile and are not stored, logged, or retained by Compass AI after your session ends. We do not maintain databases of user responses or profiles. Each session is independent and ephemeral.
          </p>

          <div className="divider" />

          <div className="section-title">User Responsibility</div>
          <p className="body-text">
            You are solely responsible for your organization's AI governance decisions. Use of this tool does not satisfy any regulatory obligation, compliance requirement, or duty of care. You agree to use Compass AI for lawful purposes only and in accordance with applicable laws and regulations.
          </p>
          <p className="body-text">
            By using Compass AI, you acknowledge that you have read and agree to these terms.
          </p>

          <div className="footer">
            <a href="/">Home</a>
            {" · "}
            <a href="/privacy">Privacy Policy</a>
          </div>
        </div>
      </div>
    </>
  );
}
